### some packages installation

In [2]:
!pip install requests

Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\alee2\appdata\local\continuum\anaconda3\envs\athena_practice\lib\site-packages (from requests)
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Installing collected packages: idna, chardet, urllib3, requests
Successfully installed chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

In [4]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
Installing collected packages: beautifulsoup4
Successfully installed beautifulsoup4-4.6.0

In [1]:
import requests as r
from bs4 import BeautifulSoup
import urllib.parse

###  testing for getting data within a month

In [90]:
# getting the data within a month (Febuary)

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker=2016-02-{}"
date = []

for i in range(1, 30) :
    if i<10 :
        i = "0"+"%s"%i
    #print(i)
    
    feb_page = page_url.format(i)
    #print(feb_page)
    feb_res = r.get(feb_page)
    feb_res.encoding = "utf-8"
    
     
    dates = "2016/02/{}"
    
    date_each = dates.format(i)
    date.append(date_each) 
    
res = r.get(page_url)
res.encoding = 'utf-8' # 調整Response obect的encoding，不然中文是亂碼
soup = BeautifulSoup(res.text, 'html5lib')

In [5]:
# tesing for integration on the whole crawler
import pprint
import pandas as pd

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker={}"
date = []
tr_list = []
month=['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

for x in range(len(month)) :
    
    if x<10 :
        x = "0"+"%s"%x
    
    for i in range(1, 30) :
        
        if i<10 :
            i = "0"+"%s"%i
            #print(i)
        
            
        feb_date = "2016-{}-{}".format(x, i)
        #date_col = []
        #date_col.append(feb_date)
        #print(date_col)
            
        feb_page = page_url.format(feb_date)
        #print(feb_page)
            
            
            
        feb_res = r.get(feb_page)
        feb_res.encoding = "utf-8"
        soup = BeautifulSoup(feb_res.text, 'html5lib')
            
        # getting out the data
            
        for i in range(3, 27):
            ii =soup.select("tr" )[i]
            tr_set = "%s"%ii
            tr_set = tr_set.replace("\n\t\t", "").replace("\xa0", "").replace("<tr>", "")\
            .replace("</tr>", "").replace('<td nowrap="">', "").replace("</td>", ",").replace("<td>", "")\
            .replace("\t", "").replace("\n\t", '').replace('\n', '').replace(" ", "")
            # tr_set is still a string now
            tr_set = tr_set.split(",") 
            # for this time, after the action of splitting, tr_set becomes a list !
            
            tr_set.insert(0,feb_date)
            tr_set.pop(16)
            tr_list.append(tr_set)
        #pprint.pprint(tr_list)
            
    df = pd.DataFrame(tr_list , columns = column_names)
        
    df
    df.to_csv('./data/{}_weather_data.csv'.format(month[i]))

In [81]:
# testing for crawling whole year data

import pprint
import pandas as pd

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker={}"
date = []

month=['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
year = [2015, 2016]

for y in year :
    
    

    for m in range(1,len(month)+1) :
        
        tr_list = []
        
        if m<10 :
            m = "0"+"%s"%m
        else :
            m = "%s"%m
        #print(m)
    
        if y == year[0] :
            if m in ['01', '03', '05', '07', '08', '10', '12'] :
                day = 31
            elif m == '02' :
                day = 28
            elif m in ['04', '06', '09', '11'] :
                day = 30
            
            
        elif y == year[1] :
            if m in ['01', '03', '05', '07', '08', '10', '12'] :
                day = 31
            elif m == '02' :
                day = 29
            elif m in ['04', '06', '09', '11'] :
                day = 30
            
            
        
        
    
        
    
        for d in range(1, day+1) :
            #print('======={}===={}============='.format(y, m))
            if d<10 :
                d = "0"+"%s"%d
        
            #print(d)
        
            
            ymd_date = "{}-{}-{}".format(y, m, d)
            #print(ymd_date)
        
            
            each_page = page_url.format(ymd_date)
            #print(each_page)
            
            each_res = r.get(each_page)
            each_res.encoding = "utf-8"
            soup = BeautifulSoup(each_res.text, 'html5lib')
            
            # getting out the data
            # every hour in one day
            try :
                for i in range(3, 27):
                                                       
                    ii =soup.select("tr" )[i]
                    tr_set = "%s"%ii
                    tr_set = tr_set.replace("\n\t\t", "").replace("\xa0", "").replace("<tr>", "")\
                    .replace("</tr>", "").replace('<td nowrap="">', "").replace("</td>", ",").replace("<td>", "")\
                    .replace("\t", "").replace("\n\t", '').replace('\n', '').replace(" ", "")
                    # tr_set is still a string now
                    tr_set = tr_set.split(",") 
                    # for this time, after the action of splitting, tr_set becomes a list !
                    
                    tr_set.insert(0,ymd_date)
                    tr_set.pop(16)
                    tr_list.append(tr_set)
            except :
                print("no record for %s"%ymd_date)
                continue
                
        #tr_list
        df = pd.DataFrame(tr_list , columns = column_names)
        
        #print(df)
        m = int(m)
        #print(m)
        df.to_csv('./data/{}_{}{}_weather_data.csv'.format(y, m, month[m-1]))

no record for 2015-09-30
no record for 2016-06-21
no record for 2016-11-02

In [79]:
for y in year :
    print(y)
    print(year.index(y))

2015
0
2016
1

In [82]:
#pprint.pprint(tr_list)
#WeatherDataSet.shape()

In [15]:
len(tr_list)

696

In [28]:
# testing for getting one page information (02-01)

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker=2016-02-01"
res = r.get(page_url)
res.encoding = 'utf-8' # 調整Response obect的encoding，不然中文是亂碼
soup = BeautifulSoup(res.text, 'html5lib')

### making a list of column names
list name : column_names

In [29]:


column_name_unformat = []
column_names = []
#soup.select("th")[9]
column_names.append('date') 

for i in range(9, 24):
    col_title_unformat = soup.select("th")[i]
    col_title = "%s"%col_title_unformat
    
    column_name_unformat.append(col_title)
    #col_title = col_title.split("<th>")[1]
    #print(col_title)
#column_name

for i in column_name_unformat :
    col_title = i.split('<th>')[1].split("</th>")[0].replace("<br/>", " ")
    
    column_names.append(col_title)
    
    #print(col_title)

   
column_names

['date',
 '觀測時間 (LST) ObsTime',
 '測站氣壓 (hPa) StnPres',
 '海平面氣壓 (hPa) SeaPres',
 '氣溫 (℃) Temperature',
 '露點溫度 (℃) Td dew point',
 '相對溼度 (%) RH',
 '風速 (m/s) WS',
 '風向 (360degree) WD',
 '最大陣風 (m/s) WSGust',
 '最大陣風風向 (360degree) WDGust',
 '降水量 (mm) Precp',
 '降水時數 (hr) PrecpHour ',
 '日照時數 (hr) SunShine',
 '全天空日射量 (MJ/㎡) GloblRad',
 '能見度 (km) Visb']

### crawling the data in cell (weather data)

the reason using range(3, 27) is the tr_record data we need begin from the fourth element(index 3) <br> and end in the 28th (index 27)

In [35]:
tr_list = []


for i in range(3, 27):
    ii =soup.select("tr" )[i] 
    tr_set = "%s"%ii
    tr_set = tr_set.replace("\n\t\t", "").replace("\xa0", "").replace("<tr>", "")\
    .replace("</tr>", "").replace('<td nowrap="">', "").replace("</td>", ",").replace("<td>", "")\
    .replace("\t", "").replace("\n\t", '').replace('\n', '').replace(" ", "")
    #print(ii)
    tr_list.append(tr_set)

In [59]:
# detecting each of the soup format (one day)

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker={}"

for i in range(1, 30) :
    if i<10 :
        i = "0"+"%s"%i
    #print(i)
    
    feb_date = "2015-06-%s"%i
    feb_page = page_url.format(feb_date)
    #print(feb_page)
    
    
    feb_res = r.get(feb_page)
    feb_res.encoding = "utf-8"
    soup = BeautifulSoup(feb_res.text, 'html5lib')

    print(len(soup.select("tr")))
    #soup.select("tr")

27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27
27

In [65]:

page_url = "http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0A9G0&stname=%25E5%258D%2597%25E6%25B8%25AF&datepicker=2016-06-21"
res = r.get(page_url)
res.encoding = 'utf-8' # 調整Response obect的encoding，不然中文是亂碼
soup = BeautifulSoup(res.text, 'html5lib')

soup.select("tr > td")

[<td>測站:C0A9G0_南港  </td>,
 <td><a href="#" id="preItem"><input height="24" src="images/buttons_l.png" type="image" width="24"/></a></td>,
 <td>觀測時間:2016-06-21</td>,
 <td><a href="#" id="nexItem"><input height="24" src="images/buttons_r.png" type="image" width="24"/></a></td>]

In [36]:
tr_list

['1,1015.0,,16.6,,94,1.0,87,,,0.0,,,,,',
 '2,1015.6,,16.2,,98,0.8,86,,,0.0,,,,,',
 '3,1016.2,,16.2,,99,0.8,84,,,0.0,,,,,',
 '4,1016.3,,15.3,,93,1.0,85,,,0.0,,,,,',
 '5,1017.4,,13.8,,94,1.4,74,,,0.0,,,,,',
 '6,1018.1,,13.6,,91,1.1,72,,,0.0,,,,,',
 '7,1018.4,,13.6,,91,1.0,56,,,0.0,,,,,',
 '8,1018.9,,13.7,,88,0.9,79,,,0.0,,,,,',
 '9,1019.5,,13.9,,89,0.9,47,,,0.0,,,,,',
 '10,1020.0,,13.8,,90,1.1,56,,,0.0,,,,,',
 '11,1020.0,,13.4,,83,1.2,49,,,0.0,,,,,',
 '12,1019.6,,13.2,,80,1.3,67,,,0.0,,,,,',
 '13,1018.8,,13.6,,75,1.1,52,,,0.0,,,,,',
 '14,1018.2,,12.9,,76,1.2,64,,,0.0,,,,,',
 '15,1017.7,,12.8,,81,1.1,59,,,0.0,,,,,',
 '16,1018.1,,12.3,,88,0.8,56,,,0.0,,,,,',
 '17,1019.0,,12.2,,87,0.9,61,,,0.0,,,,,',
 '18,1019.4,,12.2,,87,0.9,81,,,0.0,,,,,',
 '19,1019.5,,12.4,,85,1.1,85,,,0.0,,,,,',
 '20,1019.8,,12.4,,87,0.7,95,,,0.0,,,,,',
 '21,1019.7,,13.1,,82,0.8,104,,,0.0,,,,,',
 '22,1019.5,,13.1,,82,0.6,118,,,0.0,,,,,',
 '23,1019.4,,13.5,,79,0.8,91,,,0.0,,,,,',
 '24,1018.8,,13.4,,81,0.8,95,,,0.0,,,,,']

In [83]:
import pandas as pd
one_record = []

ObsTime = []
StnPres = []
SeaPres = []
Temperature = []
Td_dew_point = []
RH = []
WS = []
WD = []
WSGust = []
WDGust = []
Precp = []
PrecpHour = []
SunShine = []
GloblRad = []
Visb = []


for i in tr_list :
    one_record.append(i.split(','))
    
for i in one_record :
    ObsTime.append(i[0])
    StnPres.append(i[1])
    SeaPres.append(i[2])
    Temperature.append(i[3])
    Td_dew_point.append(i[4])
    RH.append(i[5])
    WS.append(i[6])
    WD.append(i[7])
    WSGust.append(i[8])
    WDGust.append(i[9])
    Precp.append(i[10])
    PrecpHour.append(i[11])
    SunShine.append(i[12])
    GloblRad.append(i[13])
    Visb.append(i[14])

#one_record
#ObsTime

AttributeError: 'list' object has no attribute 'split'

In [81]:
Temperature

['17.6',
 '17.3',
 '17.1',
 '16.4',
 '15.8',
 '15.1',
 '14.3',
 '13.7',
 '13.8',
 '13.9',
 '13.9',
 '14.0',
 '13.8',
 '13.7',
 '13.8',
 '13.4',
 '13.2',
 '12.6',
 '12.3',
 '12.1',
 '12.1',
 '12.0',
 '11.9',
 '11.9']

### making the data list togeter into a zip dataset

In [85]:
# using zip function

 

WeatherDataSet = list(zip(date,ObsTime,StnPres,SeaPres,Temperature,Td_dew_point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,SunShine,GloblRad,Visb))
#WeatherDataSet
df = pd.DataFrame(data = WeatherDataSet, column_names)

df

,ObsTime,StnPres,SeaPres,Temperature,Td_dew_point,RH,WS,WD,WSGust,WDGust,Precp,PrecpHour,SunShine,GloblRad,Visb
0,1,1017.3,,17.6,,94,1.2,74,,,0.0,,,,
1,2,1017.4,,17.3,,94,1.3,81,,,0.5,,,,
2,3,1017.5,,17.1,,91,1.2,69,,,0.0,,,,
3,4,1018.4,,16.4,,90,1.3,61,,,0.0,,,,
4,5,1019.6,,15.8,,88,0.9,67,,,0.0,,,,
5,6,1020.3,,15.1,,90,1.3,68,,,0.0,,,,
6,7,1021.2,,14.3,,89,1.3,68,,,1.0,,,,
7,8,1022.2,,13.7,,89,1.3,58,,,0.0,,,,
8,9,1022.4,,13.8,,91,1.3,65,,,1.5,,,,
9,10,1022.9,,13.9,,90,1.1,60,,,0.0,,,,
10,11,1022.5,,13.9,,88,1.4,59,,,1.0,,,,
11,12,1021.6,,14.0,,90,0.6,61,,,0.5,,,,
12,13,1020.9,,13.8,,91,0.8,63,,,2.5,,,,
13,14,1020.2,,13.7,,90,0.9,64,,,1.0,,,,
14,15,1020.0,,13.8,,88,0.9,62,,,0.5,,,,
15,16,1020.7,,13.4,,90,0.7,69,,,0.5,,,,
16,17,1021.8,,13.2,,89,0.9,38,,,1.0,,,,
17,18,1022.3,,12.6,,88,0.8,69,,,0.5,,,,
18,19,1023.6,,12.3,,88,1.0,70,,,2.0,,,,
19,20,1023.5,,12.1,,89,0.7,76,,,0.5,,,,
20,21,1023.4,,12.1,,90,0.7,60,,,1.5,,,,
21,22,1023.3,,12.0,,90,0.8,68,,,1.0,,,,
22,23,1023.3,,11.9,,90,1.0,70,,,1.0,,,,
23,24,1022.8,,11.9,,90,0.7,63,,,0.5,,,,

In [ ]:
# something description

ObsTime.append(one_record[0])
    StnPres.append(one_record[1])
    SeaPres.append(one_record[2])
    Temperature.append(one_record[3])
    Td_dew_point.append(one_record[4])
    RH.append(one_record[5])
    WS.append(one_record[6])
    WD.append(one_record[7])
    WSGust.append(one_record[8])
    WDGust.append(one_record[9])
    Precp.append(one_record[10])
    PrecpHour.append(one_record[11])
    SunShine.append(one_record[12])
    GloblRad.append(one_record[13])
    Visb.append(one_record[14])

In [26]:
len(soup.select("tr"))

27

In [28]:
# getting out the data and make it into a dataset

for i in tr_list :

<tr>
		<td nowrap="">24</td>
		<td>1022.8 </td>
		<td> </td>
		<td>11.9 </td>
		<td> </td>
		<td>90 </td>
		<td>0.7 </td>
		<td>63 </td>
		<td> </td>
		<td> </td>
		<td>0.5 </td>
		<td> </td>
		<td> </td>
		<td> </td>
		<td> </td>
	 </tr>